### ISSUE TITLE
Dates outside the range

### ISSUE THREAD

**Issue by mrabino1** [eth2353/eth2-staking-rewards-calculator#1] opened 2021-02-16 15:53 UTC
If a validator activated on 1/1/2021 and we use a date of 12/15/2020, it gives an error. The presents a larger issue if validators were added over different times.. 

(great tool btw!)

**Comment by eth2353** [comment] 2021-02-16 16:20
Hi, I'm having trouble reproducing the issue. I tried with the following settings:

Validator index 80000 (this validator is Eligible since 18 Jan 2021, 18:26, Active since 5 Feb 2021, 05:25)
Start date: 2020-12-01
End date: 2020-12-31

The script finishes successfully, and also prints the following to the console:
`[!] No datapoints for validator 80000`

Could you add more information to this issue? The settings you used and the entire error message would be helpful.

Thanks!

**Comment by mrabino1** [comment] 2021-02-16 16:47
Retrieving beacon chain data...:   0%|                                                                                                                                                           | 0/48 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 452, in <module>
    main()
  File "main.py", line 447, in main
    datapoints = get_all_datapoints()
  File "main.py", line 350, in get_all_datapoints
    for dp in tqdm(
  File "/home/xxxxxx/.local/lib/python3.8/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "main.py", line 214, in get_datapoints_for_slot
    raise Exception(
Exception: Error while fetching data from beacon node: {"error":"Validator index xxxxxx \u003e= balance list xxxxx","code":11,"message":"Validator index xxxxxxx \u003e= balance list xxxxxx","details":[]}

**Comment by mrabino1** [comment] 2021-02-16 16:48
I am using Prysm 1.2.1

**Comment by eth2353** [comment] 2021-02-17 09:50
Hi, just pushed a fix, can you try if it resolves the issue for you?

**Comment by mrabino1** [comment] 2021-02-17 11:14
The magic of human innovation being unleashed to society. Works great !! Thank you... This issue should be resolved now. 

(Whatever you do for a living, you are underpaid.. ;) )

**Closed** 2021-02-17 11:47 UTC
